import {
  Component,
  ChangeDetectionStrategy,
  signal,
  computed,
  inject,
  effect,
} from '@angular/core';
import { Modal, ModalContainer, ModalHeader, ModalContent, ModalFooter } from 'shared-ui';
import { Button, Input } from 'shared-ui';
import { ToastService } from 'shared-ui';
import { OrganizationService } from '../../application/services/organization.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-create-organization-modal',
  imports: [ModalContainer, ModalHeader, ModalContent, ModalFooter, Button, Input],
  template: `
    <lib-modal-container>
      <lib-modal-header>Create Organization</lib-modal-header>
      <lib-modal-content>
        <form class="create-org-form" (ngSubmit)="handleSubmit()">
          <lib-input
            label="Organization Name"
            placeholder="Enter organization name"
            [(model)]="name"
            [required]="true"
            [errorMessage]="nameError()"
            helperText="Choose a name for your organization"
          />
          <lib-input
            label="Slug"
            placeholder="organization-slug"
            [(model)]="slug"
            [required]="true"
            [errorMessage]="slugError()"
            helperText="URL-friendly identifier (lowercase, hyphens only)"
          />
          <lib-input
            label="Description"
            type="textarea"
            placeholder="Describe your organization (optional)"
            [(model)]="description"
            [rows]="3"
            helperText="Optional description of your organization"
          />
        </form>
      </lib-modal-content>
      <lib-modal-footer>
        <lib-button variant="secondary" (clicked)="handleCancel()" [disabled]="isSubmitting()">
          Cancel
        </lib-button>
        <lib-button
          variant="primary"
          (clicked)="handleSubmit()"
          [loading]="isSubmitting()"
          [disabled]="!isValid()"
        >
          Create Organization
        </lib-button>
      </lib-modal-footer>
    </lib-modal-container>
  `,
  styles: [
    `
      @reference "#mainstyles";

      .create-org-form {
        @apply flex flex-col gap-4;
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CreateOrganizationModal {
  private readonly organizationService = inject(OrganizationService);
  private readonly toast = inject(ToastService);
  private readonly router = inject(Router);
  private readonly modal = inject(Modal);

  readonly name = signal('');
  readonly slug = signal('');
  readonly description = signal('');
  readonly isSubmitting = signal(false);

  readonly nameError = computed(() => {
    const value = this.name();
    if (!value.trim()) {
      return 'Organization name is required';
    }
    if (value.trim().length < 3) {
      return 'Organization name must be at least 3 characters';
    }
    return '';
  });

  readonly slugError = computed(() => {
    const value = this.slug();
    if (!value.trim()) {
      return 'Slug is required';
    }
    // Slug format validation: lowercase, letters, numbers, hyphens only
    const slugPattern = /^[a-z0-9-]+$/;
    if (!slugPattern.test(value)) {
      return 'Slug can only contain lowercase letters, numbers, and hyphens';
    }
    if (value.length < 3) {
      return 'Slug must be at least 3 characters';
    }
    // TODO: Add async uniqueness check when backend API is ready
    return '';
  });

  readonly isValid = computed(() => {
    return !this.nameError() && !this.slugError() && this.name().trim() && this.slug().trim();
  });

  private readonly lastAutoGeneratedSlug = signal<string>('');
  private readonly slugManuallyEdited = signal(false);

  constructor() {
    // Auto-generate slug when name changes (only if not manually edited)
    effect(() => {
      const nameValue = this.name();
      if (!nameValue || this.slugManuallyEdited()) {
        return;
      }

      const newSlug = this.generateSlug(nameValue);
      this.slug.set(newSlug);
      this.lastAutoGeneratedSlug.set(newSlug);
    });

    // Track when slug is manually edited
    effect(() => {
      const slugValue = this.slug();
      const lastAutoSlug = this.lastAutoGeneratedSlug();
      // If slug differs from last auto-generated, mark as manually edited
      if (slugValue && lastAutoSlug && slugValue !== lastAutoSlug) {
        this.slugManuallyEdited.set(true);
      }
    });
  }

  /**
   * Auto-generate slug from organization name
   */
  private generateSlug(name: string): string {
    return name
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9\s-]/g, '') // Remove special characters
      .replace(/\s+/g, '-') // Replace spaces with hyphens
      .replace(/-+/g, '-') // Replace multiple hyphens with single hyphen
      .replace(/^-|-$/g, ''); // Remove leading/trailing hyphens
  }

  handleCancel(): void {
    this.modal.close();
  }

  async handleSubmit(): Promise<void> {
    if (!this.isValid()) {
      return;
    }

    this.isSubmitting.set(true);

    try {
      // TODO: Replace with actual API call when backend is ready
      // await this.organizationService.createOrganization({
      //   name: this.name().trim(),
      //   slug: this.slug().trim(),
      //   description: this.description().trim() || undefined,
      // });

      const newOrg = await this.organizationService.createOrganization({
        name: this.name().trim(),
        slug: this.slug().trim(),
        description: this.description().trim() || undefined,
      });

      this.toast.success('Organization created successfully!');
      this.modal.close();

      // Reset form
      this.name.set('');
      this.slug.set('');
      this.description.set('');
      this.lastAutoGeneratedSlug.set('');
      this.slugManuallyEdited.set(false);

      // Refresh organizations list and switch to new organization
      this.organizationService.loadOrganizations();
      if (newOrg) {
        // Wait a bit for loadOrganizations to complete before switching
        setTimeout(() => {
          this.organizationService.switchOrganization(newOrg.id);
        }, 500);
      }

      // TODO: Navigate to organization page or refresh current page
      // this.router.navigate(['/organizations', newOrg.id]);
    } catch (error) {
      console.error('Failed to create organization:', error);
      this.toast.error('Failed to create organization. Please try again.');
    } finally {
      this.isSubmitting.set(false);
    }
  }
}
