import {
  Component,
  ChangeDetectionStrategy,
  signal,
  computed,
  inject,
  effect,
} from '@angular/core';
import { Modal, ModalContainer, ModalHeader, ModalContent, ModalFooter } from 'shared-ui';
import { Button, Input } from 'shared-ui';
import { ToastService } from 'shared-ui';
import { OrganizationService } from '../../../../application/services/organization.service';
import { Router } from '@angular/router';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';

@Component({
  selector: 'app-create-organization-modal',
  imports: [ModalContainer, ModalHeader, ModalContent, ModalFooter, Button, Input, TranslatePipe],
  template: `
    <lib-modal-container>
      <lib-modal-header>{{
        'organizations.modals.createOrganization' | translate
      }}</lib-modal-header>
      <lib-modal-content>
        <form class="create-org-form" (ngSubmit)="handleSubmit()">
          <lib-input
            [label]="'organizations.modals.organizationName' | translate"
            [placeholder]="'organizations.modals.organizationNamePlaceholder' | translate"
            [(model)]="name"
            [required]="true"
            [errorMessage]="nameError()"
            [helperText]="'organizations.modals.organizationNameHelper' | translate"
          />
          <lib-input
            [label]="'organizations.modals.slug' | translate"
            [placeholder]="'organizations.modals.slugPlaceholder' | translate"
            [(model)]="slug"
            [required]="true"
            [errorMessage]="slugError()"
            [helperText]="'organizations.modals.slugHelper' | translate"
          />
          <lib-input
            [label]="'organizations.modals.description' | translate"
            type="textarea"
            [placeholder]="'organizations.modals.descriptionPlaceholder' | translate"
            [(model)]="description"
            [rows]="3"
            [helperText]="'organizations.modals.descriptionHelper' | translate"
          />
        </form>
      </lib-modal-content>
      <lib-modal-footer>
        <lib-button variant="secondary" (clicked)="handleCancel()" [disabled]="isSubmitting()">
          {{ 'common.cancel' | translate }}
        </lib-button>
        <lib-button
          variant="primary"
          (clicked)="handleSubmit()"
          [loading]="isSubmitting()"
          [disabled]="!isValid()"
        >
          {{ 'organizations.modals.createOrganization' | translate }}
        </lib-button>
      </lib-modal-footer>
    </lib-modal-container>
  `,
  styles: [
    `
      @reference "#mainstyles";

      .create-org-form {
        @apply flex flex-col gap-4;
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CreateOrganizationModal {
  private readonly organizationService = inject(OrganizationService);
  private readonly toast = inject(ToastService);
  private readonly router = inject(Router);
  private readonly modal = inject(Modal);
  private readonly translateService = inject(TranslateService);

  readonly name = signal('');
  readonly slug = signal('');
  readonly description = signal('');
  readonly isSubmitting = signal(false);

  readonly nameError = computed(() => {
    const value = this.name();
    if (!value.trim()) {
      return this.translateService.instant('organizations.modals.nameRequired');
    }
    if (value.trim().length < 3) {
      return this.translateService.instant('organizations.modals.nameMinLength');
    }
    return '';
  });

  readonly slugError = computed(() => {
    const value = this.slug();
    if (!value.trim()) {
      return this.translateService.instant('organizations.modals.slugRequired');
    }
    // Slug format validation: lowercase, letters, numbers, hyphens only
    const slugPattern = /^[a-z0-9-]+$/;
    if (!slugPattern.test(value)) {
      return this.translateService.instant('organizations.modals.slugInvalidFormat');
    }
    if (value.length < 3) {
      return this.translateService.instant('organizations.modals.slugMinLength');
    }
    // TODO: Add async uniqueness check when backend API is ready
    return '';
  });

  readonly isValid = computed(() => {
    return !this.nameError() && !this.slugError() && this.name().trim() && this.slug().trim();
  });

  private readonly lastAutoGeneratedSlug = signal<string>('');
  private readonly slugManuallyEdited = signal(false);

  constructor() {
    // Auto-generate slug when name changes (only if not manually edited)
    effect(() => {
      const nameValue = this.name();
      if (!nameValue || this.slugManuallyEdited()) {
        return;
      }

      const newSlug = this.generateSlug(nameValue);
      this.slug.set(newSlug);
      this.lastAutoGeneratedSlug.set(newSlug);
    });

    // Track when slug is manually edited
    effect(() => {
      const slugValue = this.slug();
      const lastAutoSlug = this.lastAutoGeneratedSlug();
      // If slug differs from last auto-generated, mark as manually edited
      if (slugValue && lastAutoSlug && slugValue !== lastAutoSlug) {
        this.slugManuallyEdited.set(true);
      }
    });
  }

  /**
   * Auto-generate slug from organization name
   */
  private generateSlug(name: string): string {
    return name
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9\s-]/g, '') // Remove special characters
      .replace(/\s+/g, '-') // Replace spaces with hyphens
      .replace(/-+/g, '-') // Replace multiple hyphens with single hyphen
      .replace(/^-|-$/g, ''); // Remove leading/trailing hyphens
  }

  handleCancel(): void {
    this.modal.close();
  }

  async handleSubmit(): Promise<void> {
    if (!this.isValid()) {
      return;
    }

    this.isSubmitting.set(true);

    try {
      const newOrg = await this.organizationService.createOrganization({
        name: this.name().trim(),
        slug: this.slug().trim(),
        description: this.description().trim() || undefined,
      });

      this.toast.success(this.translateService.instant('organizations.modals.createSuccess'));
      this.modal.close();

      // Reset form
      this.name.set('');
      this.slug.set('');
      this.description.set('');
      this.lastAutoGeneratedSlug.set('');
      this.slugManuallyEdited.set(false);

      // Refresh organizations list and switch to new organization
      this.organizationService.loadOrganizations();
      if (newOrg) {
        // Wait a bit for loadOrganizations to complete before switching
        setTimeout(() => {
          this.organizationService.switchOrganization(newOrg.id);
        }, 500);
      }

      // TODO: Navigate to organization page or refresh current page
      // this.router.navigate(['/organizations', newOrg.id]);
    } catch (error) {
      console.error('Failed to create organization:', error);
      this.toast.error(this.translateService.instant('organizations.modals.createError'));
    } finally {
      this.isSubmitting.set(false);
    }
  }
}
